apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/mydata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-np-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: demo-docker-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-docker-k8s
  template:
    metadata:
      labels:
        app: demo-docker-k8s
    spec:
      containers:
      - name: demo-docker-k8s
        image: pramodpatwa/demo-docker-k8s:1.0.2
        ports:
        - containerPort: 8080
        volumeMounts: 
        - name: abc 
          mountPath: /abc        
      volumes: 
      - name: abc
        persistentVolumeClaim:
          claimName: mypv-claim
